language: ruby

rvm:
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.0"
  - "jruby-9.3.2.0"
  - "ruby-head"

env:
  - COVERALL=1

cache:
  - bundler

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem install bundler
